### ISSUE TITLE
Support for Sinopia Stage and Production 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#80]
Currently we only been using Sinopia Development environment. We need to support Sinopia Stage first and then Production environments.

**Comment by jmartin-sul** [comment]
One specific thing we know we need to figure out: how to specify the application environment (e.g. dev, stage, or prod) to the code.  At present, this is mostly hardcoded, though at least one part of the code expects an operating system environment variable.  However, in #83, @jermnelson says his "preference would be the app environment would be set per DAG or in some other fashion so that we only have to run one Airflow instance for all three of Sinopia's environments, development, stage, and production."  I believe that'd preclude the use of an OS env var, as an OS env var would be shared across all three application environments, if they're all being run by one airflow instance.

**Comment by aaron-collier** [comment]
Per discussion with @jermnelson we may just need to allow the dev-airflow to monitor stage/prod SQS queues through terraform or through specific aws airflow connections

**Comment by jmartin-sul** [comment]
post-standup discussion:  one difficulty with using a single airflow instance is that there's not a clear path for how we go about testing DAG changes in stage, before deploying to prod.

e.g. if one DAG on one airflow instance is monitoring stage and prod, and we want to test a new task in just stage, before deploying to prod, how might we do that?

we'll try to enumerate the benefits and downsides of a single airflow instance with a single DAG monitoring multiple queues, vs a single airflow instance with multiple DAGs (one per each environment's queue?), vs multiple airflow instance (likely the setup most analagous to our other environments -- for example, our existing home grown workflow management system has distinct stage and prod instances, with distinct worker deployments and backing redis instances).

**Comment by jmartin-sul** [comment]
@jermnelson and I met to discuss this today, and neither of us could come up with a good answer to the pre-prod testing problem when running a single instance of Airflow to handle both stage and prod environments.  My worry was that we'd have to do something like feature flags for which tasks are enabled in which environments, for which version of a function implements an operator in a given env, etc.  Or, that we'd have to dynamically instantiate different DAG definitions for each environment.  In all those scenarios, even if the change is very small and configuration-like, we'd still be deploying a commit that hadn't been tested in stage when going to prod, which feels like an extra opportunity to introduce human error.  And versioning functionality within the code that might be better versioned in Git.

The downside of multiple Airflow instances is of course that it's more complexity to maintain, and more resourcing to pay for.  (this random person on the internet claims ["Running Airflow on AWS with the default configurations (also considering cluster is not scaling up) should cost from 5 to 7 US dollars per day"](https://towardsdatascience.com/how-to-deploy-airflow-on-aws-best-practices-63778d6eab9e) -- YMMV)

Since we hope the complexity is manageable via Helm (we're deploying to Kubernetes on AWS), and since we hope the cost of supporting two environments is not terrible, we're going to go ahead and try separate stage and prod Airflow instances.  This should give the most consistency with our other environments, and the most similarity between deploying a DAG for testing on stage and then deploying that same logic on prod.

Additionally, after meeting, I did a bit of searching to see if there was an idiomatic way to do this among Airflow users, and finally found something of an official (if slightly implied) recommendation in this [Airflow best practices doc](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#staging-environment):

> If possible, keep a staging environment to test the complete DAG run before deploying in the production. Make sure your DAG is parameterized to change the variables, e.g., the output path of S3 operation or the database used to read the configuration. Do not hard code values inside the DAG and then change them manually according to the environment.
>
> You can use environment variables to parameterize the DAG.
>
> ```
> import os
> dest = os.environ.get("MY_DAG_DEST_PATH", "s3://default-target/path/")
> ```

Which seems like support for our somewhat tentative conclusion.

One other worry:  neither @jermnelson nor I really had any concrete idea how to go about provisioning a second Airflow instance.  We were hoping @aaron-collier could give some advice on that 🙂 (as well as any other feedback on this discussion so far)

**Comment by jmartin-sul** [comment]
the docs do point out that DAGs can be [configured dynamically](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#dynamic-dags-with-external-configuration-from-a-structured-data-file), but they also [advise minimizing DAG complexity](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#reducing-dag-complexity).
